export const SUBMIT_FORM_REQUEST = 'SUBMIT_FORM_REQUEST';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAILURE = 'SUBMIT_FORM_FAILURE';

export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const UPLOADER_START_UPLOAD = 'UPLOADER_START_UPLOAD';
